name: CI

on:
  push:
    branches: [ task4 ]
  pull_request:
    branches: [ task4 ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: |
        mkdir task4/3rdparty
        git clone https://github.com/google/googletest.git task4/3rdparty/
        mkdir task4/build
        cd task4/build
        cmake -DCMAKE_INSTALL_PREFIX=exe_files ..
        make
        make install

